
input.onButtonPressed(Button.A, () => {
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC0))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC1))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC2))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC3))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC4))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC5))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC6))
    basic.showNumber(iKB1z.ADC(iKB1ADC.ADC7))

})

input.onButtonPressed(Button.B, () => {
    basic.showNumber(iKB1z.In(pinx.D0))
    basic.showNumber(iKB1z.In(pinx.D1))
    basic.showNumber(iKB1z.In(pinx.D2))
    basic.showNumber(iKB1z.In(pinx.D3))
    basic.showNumber(iKB1z.In(pinx.D4))
    basic.showNumber(iKB1z.In(pinx.D5))
    basic.showNumber(iKB1z.In(pinx.D6))
    basic.showNumber(iKB1z.In(pinx.D7))
    basic.pause(1000)
    basic.showNumber(iKB1z.In_p(pinx.D0))
    basic.showNumber(iKB1z.In_p(pinx.D1))
    basic.showNumber(iKB1z.In_p(pinx.D2))
    basic.showNumber(iKB1z.In_p(pinx.D3))
    basic.showNumber(iKB1z.In_p(pinx.D4))
    basic.showNumber(iKB1z.In_p(pinx.D5))
    basic.showNumber(iKB1z.In_p(pinx.D6))
    basic.showNumber(iKB1z.In_p(pinx.D7))
})

input.onButtonPressed(Button.AB, () => {
    iKB1z.out(pinx.D0, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D1, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D2, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D3, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D4, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D5, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D6, st.ON)
    basic.pause(500)
    iKB1z.out(pinx.D7, st.ON)
    basic.pause(1000)
    iKB1z.out(pinx.D0, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D1, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D2, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D3, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D4, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D5, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D6, st.OFF)
    basic.pause(500)
    iKB1z.out(pinx.D7, st.OFF)
})

iKB1z.Motor(iKB1Motor.Forward, 50)
basic.pause(500)
iKB1z.Motor(iKB1Motor.Backward, 50)
basic.pause(500)
iKB1z.Spin(iKB1Spin.Left, 50)
basic.pause(500)
iKB1z.Spin(iKB1Spin.Right, 50)
basic.pause(500)
iKB1z.Turn(iKB1Turn.Left, 50)
basic.pause(500)
iKB1z.Turn(iKB1Turn.Right, 50)
basic.pause(500)
iKB1z.AO()



